name: Deploy to Firebase App Hosting
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest
          install_components: 'beta'

      - run: npm ci
      - run: npm run build

      - name: Deploy to Cloud Run (App Hosting backend)
        run: |
          gcloud run deploy bukgazua \
            --source . \
            --project=angels-touch-e1lwx \
            --region=asia-east1 \
            --allow-unauthenticated
