name: Deploy to Firebase App Hosting

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write          # OIDC 사용

    steps:
      - uses: actions/checkout@v4

      - name: Google Cloud 인증
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: gcloud & Firebase CLI 셋업
        uses: google-github-actions/setup-gcloud@v2   # gcloud SDK 설치
        with:
          install_components: 'beta'                  # App Hosting은 아직 beta

      - name: 의존성 설치 및 빌드
        run: |
          npm ci
          npm run build

      - name: Firebase App Hosting 배포
        run: |
          npx firebase-tools apphosting:backends:deploy live \
            --project angels-touch-e1lwx \
            --location us-central1