name: Deploy to Firebase App Hosting
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Install & build
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase App Hosting
        run: npx firebase-tools hosting:channel:deploy live --project=angels-touch-e1lwx
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ""
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ""
          FIREBASE_CLI_EXPERIMENTS: "serviceAccountImpersonation"
