
name: Deploy to Firebase App Hosting
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      # ✅ 최신 SDK + App Hosting 컴포넌트 설치
      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest
          install_components: beta,apphosting

      - run: npm ci
      - run: npm run build

      # ✅ 백엔드명, 프로젝트, region 모두 맞춤
      - run: |
          gcloud beta apphosting backends deploy bukgazua \
            --project=angels-touch-e1lwx \
            --region=asia-east1 \
            --source .
