name: Deploy to Firebase App Hosting
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      name: Deploy to Cloud Run
  run: |
    gcloud run deploy bukgazua \
      --source . \
      --project=angels-touch-e1lwx \
      --region=asia-east1 \
      --allow-unauthenticated \
      --build-service-account=cb-bukgazua@angels-touch-e1lwx.iam.gserviceaccount.com
