name: Deploy to Firebase App Hosting
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/783936695295/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'firebase-app-hosting-compute@careconnect-app.iam.gserviceaccount.com'

      - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v1
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: careconnect-app
